### ISSUE TITLE
CSS深入理解之absolute

### ISSUE THREAD

**Issue by Anderson-James-oss** [Anderson-James-oss/blog#10]
## absolute与float

[Issise9深入理解float](https://github.com/koalajun/blog/issues/9)已经提到过，**float** 具有包裹性和破坏性； **absolute** 有着同样的作用和效果；

**包裹性**

```html
<div id="box" class="box"><img src="http://img.mukewang.com/54447b06000171a002560191.jpg" width="256" height="191"></div>
```
![jz1](https://user-images.githubusercontent.com/28972785/28771309-e4ba8c2e-7614-11e7-9481-f79225715609.gif)

**破坏性**
![jz2](https://user-images.githubusercontent.com/28972785/28771312-e8f792d2-7614-11e7-857c-9003eb3ee916.gif)

## absolute行为表现

**脱离文档流**

```html
       <img src="img/3..jpeg" alt="" width="250" height="375">
	<img class="img-2" src="img/2.jpg" alt="" width="250" height="375">
	<img src="img/1.jpg" width="300" height="250">
```
![image](https://user-images.githubusercontent.com/28972785/28772251-2dee063e-7618-11e7-977f-483a552982be.png)

**CSS给中间妹子加上absolute**

```css
.img-2 {
   position: absolute;
}
```
![image](https://user-images.githubusercontent.com/28972785/28772299-5a15cc6a-7618-11e7-8edc-46b75a0ba0e6.png)

> 可以看到第二张脱离了文档流，第三张移位图片

**Q1：这个时候第二张脱离文档流为什么还在原来的位置？(并没有给父元素添加relative)**
**Q2：这个时候第二张图片absolute化了，那它的display会不会和float一样block化？**

### 去浮动

**float** 和 **absolute** 是不能同时存在的，如果两个同时存在会去除float

改写上面的CSS

```CSS
.img-2{
			float: left;
		}
```
![image](https://user-images.githubusercontent.com/28972785/28772905-2b5cea78-761a-11e7-8766-f1211d2ce7d5.png)
第二张图片会浮动到最右边，如果我们**加上absolute**，会按照absolute样式走(去浮动)

```css
.img-2{
			position: absolute;
			float: left;
		}
```
![image](https://user-images.githubusercontent.com/28972785/28772979-649c894c-761a-11e7-9f5a-99c20435c84b.png)

### 位置跟随

**无依赖的的absolute跟随性是指：在普通元素时候待在什么位置，absolute之后依然在什么位置**

absolute具有位置跟随的特性，什么意思呢？就是之前元素是一个block(单独占据一行，当它被absolute的时候，该元素依然占据一行)，看例子

修改上面的CSS，给第二张图片**display:block**
```css
.img-2{
			display: block;
		}
```
![image](https://user-images.githubusercontent.com/28972785/28773323-a67da214-761b-11e7-83f9-003b79a6bd9a.png)

可以看到该元素单独占据一行，那么这时候给第二张图片加上absolute会怎样？

```css
.img-2{
			display: block;
			position: absolute;
		}
```

![image](https://user-images.githubusercontent.com/28972785/28773432-14c524ae-761c-11e7-8b8d-c54f448c2fea.png)

这时候第二张脱离文档流，但是依然在原来的位置显示。对于inline-block的元素一样**位置跟随**

**看张鑫旭老师的例子(火狐下测试)**
![jz3](https://user-images.githubusercontent.com/28972785/28773601-d5434b34-761c-11e7-911e-4f9cdc8739c1.gif)

> 在chrome下测试会有个问题，就是在点击元素block->absolute化之后，再点击“撤销block”不起作用，主要是因为在chrome机制下面，如果元素absolute化之后的元素，再去改变display是不会有任何渲染的。

到这里上面的Q1和Q2你应该知道答案了吧；

**注意：IE7浏览器**
**IE7浏览器下任何绝对定位的元素都会inline-block化，所以从来不会出现换行显示，只会跟随显示**
**解决办法：**

在需要绝对定位的元素外面套一层div

```html
    <img src="img/1.png" alt="">
   <div><img src="img/2.png" alt=""></div>
   <img src="img/3.png" alt="">
```

**说这么多有什么鸟用呢？**

现在我们来看一下我项目中遇到的使用场景：

**场景1**
![image](https://user-images.githubusercontent.com/28972785/28774558-8ba3a15a-7620-11e7-8721-a3eb141b0b63.png)

大家可以看到上面的红色的字母`HOT`，这个相信大家一看就想到怎么写，一般都会这样写

```HTML
<a href="javascript:;" value="">
        <i class="icon icon-hot"></i>
    奥迪</a>
```

```CSS
a {
	    position: relative;
	    margin-right: 3px;
	}

 .icon.icon-hot {
   	       position: absolute;
   	       top: -14px;
   	       right: -18px;
   	       width: 29px;
   	       height: 19px;
   	       background-position: -464px -147px;
   	   }
   	   .icon {
   	       display: inline-block;
   	       background-image: url(../img/icon.png);
   	       background-repeat: no-repeat;
   	       background-color: transparent;
   	   }
```

图标的父级relative，图标本身absolute，top/bottom/left/right进行定位

在这里我们完全你可以用独立的absolute去实现，刚才那样写确实挺好没有兼容性问题，但是有点啰嗦
独立的absolute去实现：

```css
.icon.icon-hot {
   	       /*position: absolute;*/
   	       width: 29px;
   	       height: 19px;
   	       background-position: -464px -147px;
   	   }
   .icon {
   	       display: inline-block;
   	       background-image: url(../img/icon.png);
   	       background-repeat: no-repeat;
   	       background-color: transparent;
   	   }
```

我们一步一步看：

**第一步：**这里没有给父元素relative，也没有给图标absolute，正常显示是这样
![image](https://user-images.githubusercontent.com/28972785/28775902-d418cde2-7626-11e7-9d6c-8a30415ca079.png)

**第二步：** 我们给图标加上absolute，你会发现这时候图标脱离文档流(不占据空间)
![image](https://user-images.githubusercontent.com/28972785/28775979-26a0deba-7627-11e7-9962-1958baab4cfb.png)

**第三步：**  使用margin微调位置
![image](https://user-images.githubusercontent.com/28972785/28776056-7adcfb9e-7627-11e7-97d9-4d2adde558c0.png)

这时候你会发现怎么调margin-right都不会生效，只有margin-left生效，但是如果字数不一“奥迪迪”这样就无法控制自适应，**其主要原因还是位置跟随，无依赖的的absolute跟随性是指：在普通元素时候待在什么位置，无依赖absolute之后依然在什么位置**，因为位置跟随在其最左边，所以字数变化不能自适应。如何让图标位置跟随在最右边呢？

**HTML的代码结构就显得特别重要了(：在普通元素时候待在什么位置，无依赖absolute之后依然在什么位置)**

```html
<a href="javascript:;" value="">奥迪迪<i class="icon icon-hot"></i> </a>
```
![image](https://user-images.githubusercontent.com/28972785/28776570-b5057ee8-7629-11e7-8ae3-aee24711a080.png)

**场景2**

![jz4](https://user-images.githubusercontent.com/28972785/28803371-92b298d4-768e-11e7-8194-fa8dc869b9af.gif)

同样原理位置跟随；

```html
<div class="constr">
		<div class="constr-slider">
			<div class="course-sidebar-type"></div>
            <div class="course-sidebar-search">
                <ul id="result" class="course-sidebar-result">
                	<li><a href="http://www.imooc.com/view/121">分享：CSS深入理解之float浮动</a></li>
                    <li><a href="http://www.imooc.com/view/118">案例：CSS圆角进化论</a></li>
                    <li><a href="http://www.imooc.com/view/93">案例：CSS Sprite雪碧图应用</a></li>
                    <li><a href="http://www.imooc.com/view/77">案例：CSS3 3D 特效</a></li>
                    <li><a href="http://www.imooc.com/view/57">案例：如何用CSS进行网页布局</a></li>
                </ul>
            	<input class="course-search-input" placeholder="课程搜索">
            	<a href="javascript:" class="course-search-btn">搜索</a>
            </div>
		</div>
	</div>
```

```css
body { margin: 0; font: 14px/1.4 "Microsoft YaHei"; background-color: #EDEFF0; }
		.constr{
			width: 1200px;
		    max-width: 80%;
		    margin-left: auto;
		    margin-right: auto;
		    padding-bottom: 300px;
	        overflow: hidden;
		}
        .constr-slider{
        	width: 262px;
        	float: left;
        }
        .constr-slider > div{
        	border: 1px solid #e6e8e9;
    	    box-shadow: 0px 1px 2px #d5d7d8;
    	    background-color: #fff;
        }
        .course-sidebar-type {
            height: 380px;
        }
    	.course-sidebar-search {
    	    margin-top: 20px;
    	    overflow: hidden;
    	}
        .course-search-input{
        	width: 200px;
        	line-height: 18px;
        	padding: 10px;
        	margin: 0;
        	border:0 none;
        	font-size: 12px;
        	font-family: inherit;
        	float: left;
    	}
    	.course-sidebar-search.focus { border-color: #2ea7e0; }
    	.course-search-input:focus { outline: 0 none; }
    	.course-search-input::-ms-clear { display: none; }
    	.course-search-btn {
    	    width: 38px;
    	    height: 38px;
    	    float: right;
    	    background: url(http://img.mukewang.com/545305ba0001f3f600380076.png);
    	    text-indent: -9em;
    	    overflow: hidden;
    	}
    	.focus .course-search-btn { background-position: 0 -38px; }
    	.course-sidebar-result{
    		display: none;
    		position: absolute;
    		width: 260px;
    		margin: 39px 0 0 -1px;
    		padding-left: 0;
    		list-style-type: none;
    		border: 1px solid #e6e8e9;
    		background-color: #fff;
    		box-shadow: 0px 1px 2px #d5d7d8;
    		font-size: 12px; 
    	}
    	.course-sidebar-result > li:hover { background-color: #f9f9f9; }
        .course-sidebar-result > li { line-height: 30px; padding-left: 12px; }
        .course-sidebar-result a { display: block; color: #5e5e5e; text-decoration: none; }
        .course-sidebar-result a:hover { color: #000; }
```

```js
(function() {
    		var input = document.getElementsByTagName("input")[0],
    		    result = document.getElementById("result");
    			
    		if (input && result) {
    			input.onfocus = function() {
    				this.parentNode.className = "course-sidebar-search focus";
    				if (this.value != "") {
    					// show datalist
    					result.style.display = "block";
    				}
    			};
    			input.onblur = function() {
    				if (this.value == "") {
    					this.parentNode.className = "course-sidebar-search";
    				}
    				// hide datalist
    				result.style.display = "none";
    			};
    			
    			// IE7 that wrap a DIV for avoid bad effect from float
    			if (!document.querySelector) {
    				var div = document.createElement("div");
    				input.parentNode.insertBefore(div, input);
    				div.appendChild(result);
    			}
    			// events of datalist
    			if ("oninput" in input) {
    				input.addEventListener("input", function() {
    					if (this.value.trim() != "") {
    						result.style.display = "block";
    					} else {
    						result.style.display = "none";
    					}
    				});
    			} else {
    			    // IE6-IE8
    				input.onpropertychange = function(event) {
    					event = event || window.event;
    					if (event.propertyName == "value" && /focus/.test(this.parentNode.className)) {
    						if (this.value != "") {
    							result.style.display = "block";
    						} else {
    							result.style.display = "none";
    						}
    					}
    				}
    			}
    		}

    	})();
```
