### ISSUE TITLE
H5专题页系列一zepto.fullpage整体框架篇

### ISSUE THREAD

**Issue by Anderson-James-oss** [Anderson-James-oss/blog#5]
## H5专题页整体概述

先看两个之前项目的例子：
![h5](https://user-images.githubusercontent.com/28972785/28047386-419026c4-661c-11e7-82ef-48779f82a952.png)

[现场H5](https://subject.m.autohome.com.cn/dealer/2017/share/beijingshow/)

> 一个完整的H5专题应该做好以下几点：适配、动画、背景音乐、loading、分享、[统计]，有些前端需要配合后端加统计

该专题都是整屏滑动翻页的，这属于单页滚动，相对比较简单，对于这种移动端专题，我选择了`zepto.fullpage`作为基础框架，小型轻量

## zepto.fullpage
[点这里zepto.fullpage的github](https://github.com/yanhaijing/zepto.fullpage)

**兼容性**  
 可以看到它的兼容性还是很好的，如果兼容性不行可能就被一票否决了

![image](https://user-images.githubusercontent.com/28972785/28056338-46312d26-664f-11e7-8e8b-2376a034e764.png)

 **布局结构**
在README上可以很清楚看到说明 **快速上手**

**HTML**

```HTML
<div class="wp">
    <div class="wp-inner">
        <div class="page page1">1</div>
        <div class="page page2">2</div>
        <div class="page page3">3</div>
        <div class="page page4">4</div>
    </div>
</div>
```
**你一定会很疑惑，我必须这样写吗?，是固定的吗?我不想叫它`wp`可以么？**

**CSS**

**父容器需是固定高度**，并且溢出为隐藏，fullpage会使用父元素的宽度和高度。

```CSS
.wp{
    overflow: hidden;            
}
```
**这里的固定高度是多少呢?**

**js**

```js
$('.wp-inner').fullpage();
```
**为什么是`wp-inner`，而不是`wp`或者`page`呢？**

> 其实当你使用的时候会发现不是那么so easy，我们只有做到知其所以然才能更好的去使用它，对于源码只有233行的代码，小菜的我还是拜读了一下，接下来从使用和源码的角度介绍一下**zepto.fullpage**的使用。

### 首先从HTML结构来说

布局结构确实是固定不变的，主要是源码已经通过这样的固定DOM树来进行计算取值；但是类名还是随意写的，除了`page`这个类是固定的，下面从源码的角度来解释一下Why?

**固定高度**
这里的固定高度，其实是不同屏幕下的屏幕高度，其实这个高度就是单页的高，拿到这个高度才能做到单页面滚动，才能知道每次滚动多少。

首先看一下zepto.fullpage的调用：

```js
$('.wp-inner').fullpage({});
```
可以看到通过`$('.wp-inner')`来调用的，为什么不是`wp`呢？看源码

![image](https://user-images.githubusercontent.com/28972785/28056988-2f2b4880-6651-11e7-8bfb-fb3d00124406.png)

这里通过`wp-inner`的父节点的高度，来为每一个page设置高度；这样正是作者为什么说`父容器需是固定高度，并且溢出为隐藏`。
在作者的Demo中，你会发现作者都是通过`absolute`来定位`wp`元素，这使得获取父元素和屏幕高度一样大，然而我觉得 上去就来个绝对定位，有点太重了。其实这种方法很多，我选择了HTML，body，wp都是100%高，主要原因是一般这样的专题都是比较单一的；

```css
.wp{
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0; 
    overflow: hidden;        
}
```
或者

```css
	html,body,.wp{ 
			width: 100%;
			height: 100%;
                        overflow:hidden;
		}
```
都可以获取到屏幕高度设置给每一个page。

![image](https://user-images.githubusercontent.com/28972785/29250043-fc4ac788-806d-11e7-88b7-df7ccbfbfa41.png)

**单页面滑动的过渡效果**
可以看到滑动是有过渡效果的，不是很生硬，其实在CSS里面我们需要加一些固定类名的CSS，代码：

```css
.fullPage-wp{   
    -webkit-transform: translate3d(0,0,0);     
    transform: translate3d(0,0,0);     
}
.fullPage-wp:after {
    display: block;
    content: ' ';
    height: 0;
    clear: both;
}
.fullPage-wp.anim{
    -webkit-transition: all 500ms ease-out 0s;
    transition: all 500ms ease-out 0s; 
}
```
这里的固定类名不是我们自己定义的，在fullpage源码里面为我们自动加的，它会自动给`wp-inner`这层的DOM上加上该类名，当该页面滑动的时候添加`anim`类
![image](https://user-images.githubusercontent.com/28972785/28059332-80daae5a-6656-11e7-940c-4abf04ab1773.png)

![image](https://user-images.githubusercontent.com/28972785/28059288-53c59754-6656-11e7-9e2f-2a58ba5b145a.png)

**page页面**
在不同的page页下面可以为不同页面设置不同背景。
对于当前显示的页面，该Js也会为当前页面加上`.cur`这个类
![image](https://user-images.githubusercontent.com/28972785/28059685-8e76dc68-6657-11e7-844b-a908c919ca6a.png)
通过该`cur`这个类，我们可以控制动画的显示和隐藏(动画章节会细说)

### zapto.fullpage相关控制API

通过方法，可以改变fullPage内部的状态，fullPage的方法列表如下：

* update 
此方法会重新计算和渲染每屏的高度，当你发现如果每屏的高度有问题时，手动调用下此方法就可以了
* moveTo 
切换到指定屏，如果指定的屏数大于屏总数或小于0，都会做修正处理 
该方法接收两个参数： 
 next {Number} 必须 要切换到的屏的索引 
anim {Bollean} 可省略 是否有动画 默认为没有动画效果
* movePrev 向前一屏
* moveNext 向后一屏
* start 
开启切换功能，和stop配合使用。每次调用start时都会调用holdTouch 
丰富页面功能，比如到了某页需要点击某个元素后才能到下一页的时候 这个就派上用场了
* stop 
关闭切换功能，和start配合使用。每次调用stop时都会调用unholdTouch
* getCurIndex 
获取当前位于第几屏的方法（第一屏的索引为0） 
return {Number} 当前位于第几屏
* holdTouch 
监控页面触摸，页面的touchmove事件会被阻止掉，默认开启
* unholdTouch 释放页面触摸

**判断当前是哪一页**，通过cur和next双重去判断

小tips：如果总页面4页，控制第三屏不能滚动，且从最后一张开始的话也是第三屏不能滚动；通过cur和next共同控制

```js
     beforeChange:function(e){
             if (e.cur == 1 && e.next == 2) {
                $.fn.fullpage.stop();
             }
             if (e.cur == 3 && e.next == 2) {
                $.fn.fullpage.stop();
             }
          }
```
$.fn.fullpage.stop();和$.fn.fullpage.start();分别控制屏幕是否能滚动

[参考链接](https://lzw.me/a/h5-myflyme.html)
