### ISSUE TITLE
移动端适配一适配方案

### ISSUE THREAD

**Issue by Anderson-James-oss** [Anderson-James-oss/blog#7]
## 适配方案

* 固定高度，宽度自适应
* 固定宽度，ViewPort缩放
* rem做单位

### 固定高度，宽度自适应

这种个人认为称不上适配，它适合在很小的设计稿下（如 320px）作为参照进行布局。垂直方向高度和间距都是用定值，水平方向可以混合使用定值、百分比或者弹性布局；这样造成的现象就是，在大屏幕下会横向拉伸的或者填充空白，这时候间距就会增加；图像元素可以根据容器写定值或者background-size缩放。

这种方法使用了完美视口：

```html
<meta name="viewport" content="width=device-width,initial-scale=1">
```

**样式中的尺寸都按照视觉稿二分之一大小设置(2倍的设计稿)**

* 以小宽度作为参照是因为如果布局满足了小宽度的摆放(比如：在 iphone4下)
![image](https://user-images.githubusercontent.com/28972785/28159948-413a9bc4-67f1-11e7-9a54-248975c1ce16.png)

红框的宽度大小**margin-left:9px**，这时候在iphone 6 plus下是这样的：
![image](https://user-images.githubusercontent.com/28972785/28160079-acbc3e8e-67f1-11e7-87a5-090fe5144918.png)
可以发现左边依然是定值**margin-left:9px**，但是右边已经填充空白，反过来，如果在比iphone4还小的屏幕下就可能造成“挤坏了”。
![image](https://user-images.githubusercontent.com/28972785/28160265-3569c8b4-67f2-11e7-9621-2e7f39b9cd31.png)

* 在小宽度为参考的布局，如果是大宽度的图像该怎么办呢
* 320px 过于窄小，不利于页面的设计；

### 固定宽度，ViewPort缩放
这种适配对于开发者来说比较方便，比如：640的设计稿，viewport width的值就等于640，页面宽度都是640，开发尽管按照设计稿，量的多少就写多少px；
```html
meta name="viewport" content="width=640,initial-scale=0.5,maximum-scale=0.5,minimum-scale=0.5,user-scalable=no">
```
640 是我们根据设计图定下的，0.5 是根据屏幕宽度动态生成的。

**优点：**

开发简单    缩放交给浏览器，完全按视觉稿切图。
还原精准    绝对等比例缩放，可以精准还原视觉稿（不考虑清晰度的情况下）。
测试方便    在PC端即可完成大部分测试，手机端只需酌情调整一些细节（比如图标、字体混合排列时，因为字体不同造成的对齐问题）。

**存在的问题：**

像素丢失     对于一些分辨率较低的手机，可能设备像素还未达到指定的 viewport 宽度，此时屏幕的渲染可能就不准确了。比较常见的是边框“消失”了，不过随着手机硬件的更新，这个问题会越来越少的。
缩放失效     某些安卓机不能正常的根据 meta 标签中 width 的值来缩放 viewport，需要配合 initial-scale 。
文本折行    存在于缩放失效的机型中，某些手机为了便于文本的阅读，在文本到达 viewport 边缘（非元素容器的边缘）时即进行折行，而当 viewport 宽度被修正后，浏览器并没有正确的重绘，所以就发现文本没有占满整行。一些常用的段落性文本标签会存在该问题。

这存在的问题比较突出，个人感觉比较影响用户体验；

### 利用 rem 布局

**rem( html 的 font-size)**，页面任何需要弹性适配的元素，尺寸均换算为 rem 进行布局；当页面渲染时，根据页面有效宽度进行计算，调整 rem 的大小，动态缩放以达到适配的效果。

这种适配需要动态的改变html 的 font-size，我们公司采用媒体查询对不同宽度屏幕范围设置不同的font-size，然后通过Sass或者less写方法进行转换成rem单位；

```css
@charset "UTF-8";

@media screen and (min-width: 320px) and (max-width:374px) {
    html {
        font-size:16px
    }
}

@media screen and (min-width: 375px) and (max-width:479px) {
    html {
        font-size:18px
    }
}

@media screen and (min-width: 480px) and (max-width:539px) {
    html {
        font-size:20px
    }
}

@media screen and (min-width: 540px) and (max-width:639px) {
    html {
        font-size:24px
    }
}

@media screen and (min-width: 640px) {
    html {
        font-size:28px
    }
}
```
Sass：

```css
//px转换rem(兼容旧版本方法)
@function ptr($px, $default:16px){
  @return $px / $default * 1rem;
}

//px转换rem（设计稿实际尺寸）
@function ptrd($px, $default:16px){
  @return $px / $default / 2 * 1rem;
}

//px转换rem（设计稿实际尺寸, 针对6p）
@function ptrp($px, $default:16px){
  @return $px / $default / 3 * 1rem;
}
```
一般都是用的ptrd()转换的(2倍的设计稿)，之前刚接触的时候蛋疼过这个方法：
该方法可以认为是按照320宽的手机下算出多少rem，然后其他屏幕下，由于font-size不同，rem自然会跟着变了；不过这样写可能会产生不清晰；

**优点：**
* 能解决 DPR 引起的“1像素”问题。
* 向后兼容较好，即便屏幕宽度增加、PPI 增加该方案依旧适用。

**缺点：**
* 某些Android机会丢掉 rem 小数部分。
* 需要预编译库进行单位转换
