### ISSUE TITLE
CSS深入理解float浮动

### ISSUE THREAD

**Issue by Anderson-James-oss** [Anderson-James-oss/blog#9]
# float的设计初衷——实现文字环绕效果
**float**设计的初衷并不是为了高大上的布局，而是为了**实现文字环绕效果**。

避免出现图片一行，文字一行的情况
![image](https://user-images.githubusercontent.com/28972785/28420045-75b32bb2-6d93-11e7-92f0-3ee3a59bdbb9.png)

**栗子：**

```html
        <style>
		.con{
			width: 600px; margin: 16px auto; line-height: 1.5; font-size: 14px; 
		}
		.float-left { float: left; margin: 0 10px 5px 0; }
	</style>
      <div class="con">
		<img class="float-left" src="img/1.png" alt="pic">
		<p>人物、情节、环境是小说的三要素。情节一般包括开端、发展、高潮、结局四部分，有的包括序幕、尾声。环境包括自然环境和社会环境。 小说按照篇幅及容量可分为长篇、中篇、短篇和微型小说（小小说）。按照表现的内容可分为神话、科幻、公案、传奇、武侠、言情、同人、官宦等。按照体制可分为章回体小说、日记体小说、书信体小说、自传体小说。按照语言形式可分为文言小说和白话小说。</p>
		<p>“小说”一词最早出现于《庄子·外物》：「饰小说以干县令，其于大达亦远矣。」庄子所谓的「小说」，是指琐碎的言论，与今日小说观念相差甚远。直至东汉桓谭《新论》：「小说家合残丛小语，近取譬喻，以作短书，治身理家，有可观之辞。」班固《汉书．艺文志》将「小说家」列为十家之后，其下的定义为：「小说家者流，盖出于稗官，街谈巷语，道听途说[4]之所造也。」才稍与今日小说的意义相近。</p>
	</div>
```

![image](https://user-images.githubusercontent.com/28972785/28420583-29bba4da-6d95-11e7-8212-85eb2658b998.png)

## float特性——包裹与破坏
**包裹：**是指浮动的元素大小刚好给包裹起来，这也正是江湖传闻的 [BFC](https://www.w3cplus.com/css/understanding-block-formatting-contexts-in-css.html) 
表现特征：
* 收缩(大小刚好和元素大小一样)
* 坚挺(高度和元素高度刚好一样高)
* 隔绝(里面的元素怎么变化都不会影响外面的)

**破坏：**
没有浮动时候表现入下图
![image](https://user-images.githubusercontent.com/28972785/28422614-29440262-6d9b-11e7-9eb0-075103d4c314.png)
**float之后，父元素高度塌陷**
![image](https://user-images.githubusercontent.com/28972785/28422641-3f195ae2-6d9b-11e7-891b-52e5d81d045d.png)

## 清除浮动(准确来说是清除浮动带来的影响)

1\.  **底部插入clear:both**

**底部插入clear:both**在底部加上clear,但是跟外部依然是能直接接触的，比如:margin重叠
**clear通常两种形式**
* 底部插入HTML block水平元素
```css
%clearfloat {
  display: block;
  clear: both;
  height: 0;
  overflow: hidden;
}
```
**或者**

```css
&::after,&::before{
  	    content: " ";
          visibility: hidden;
          display: block;
          height: 0;
          clear: both;
  	}
```

2\.  **父元素BFC(IE8+)或者haslayout(IE6/IE7)**

**父元素BFC(IE8+)或者haslayout(IE6/IE7)**里面的任何生命都不会对外部产生影响
```css
.clearfix {
  	    *zoom: 1;
  	}
```
zoom：1 触发IE hasLayout。

考虑到兼容性：
![image](https://user-images.githubusercontent.com/28972785/28424158-7e5a5342-6d9f-11e7-8f7d-0c54b0c9f012.png)
![image](https://user-images.githubusercontent.com/28972785/28424209-9d793fb8-6d9f-11e7-9bf0-c48b014e0837.png)

## 不要滥用clearfix
**clearfix应用在包含浮动子元素的父级元素上**，不要不是父元素的也都加上，因为乱入烦人haslayout会让IE6/IE7显得更魔性，做出更出个的事情；

## float的block化和去空格

* float的block化

```html
<span style="float: left;">Hello float</span>
```
![image](https://user-images.githubusercontent.com/28972785/28487596-7acc525c-6ec6-11e7-95d0-52735d6f41b2.png)

虽然变成了block元素，但是并不会和普通的block元素表现一样，别忘了float的特性**收缩、坚挺、隔绝**

* float的去空格化

```html
<div class="main">
		<button>btn1</button>
                <button>btn2</button>
		<button>btn3</button>
</div>
```

![image](https://user-images.githubusercontent.com/28972785/28487649-baf1463e-6ec7-11e7-8ab1-e300a405c894.png)

```css
button{
		float: left;
}
```
![image](https://user-images.githubusercontent.com/28972785/28487663-1b33747c-6ec8-11e7-96b6-e23b7caac5ad.png)
空格则会消失，且回车造成的空格也没有占据，如果刻意加上空格呢

```html
<div class="main">
		<button>btn1</button>&nbsp;
		<button>btn2</button>&nbsp;
		<button>btn3</button>
	</div>
```
![image](https://user-images.githubusercontent.com/28972785/28487679-88f0a656-6ec8-11e7-9311-d01236b14ed2.png)

空格会跟随在后面，还是浮动的初衷**文字环绕效果**

## float流体布局

* **文字环绕效果变形**

![image](https://user-images.githubusercontent.com/28972785/28488680-4974e478-6ee2-11e7-9ce4-9558f136303f.png)

```html
       <div class="con">
		<div class="left">this is left</div>
		<div class="right">this is right</div>
		<div class="center">center</div>
	</div>
```
> float:left（左边）
float:right（右边）
text-align:center（中间）
这个顺序需要注意，文字环绕效果的变形，需要浮动的元素先浮动，不然会出现这样的效果:
换一下顺序：

```html
       <div class="con">
		<div class="left">this is left</div>
               <div class="center">center</div>
		<div class="right">this is right</div>
	</div>
```
![image](https://user-images.githubusercontent.com/28972785/28488730-07f9ce7c-6ee3-11e7-8244-d75f49679a96.png)

* **文字环绕衍生——单侧固定**

![image](https://user-images.githubusercontent.com/28972785/28500358-789c773a-6ff9-11e7-8b32-a33495820c6a.png)

> 大家一看就会想到**头像部分(width+float),描述部分(padding-left/margin-left)**

CSS:

```CSS
 .left{
        	width:100px;
        	float: left;
        	margin-right: 20px;
        }
        .right{
        	margin-left: 120px;
        }
```

```html
<div class="box-con">
	    	<a href="javaScript;" class="left">
	    		<img src="img/2.png" alt="">
	    	</a>
	    	<div class="right">
	    		<p>西魏年间乱世混战，大批平民在战乱中沦为
 奴隶，命如草芥。奴籍少女楚乔（赵丽颖饰）被送入人猎场供贵族娱乐射杀，幸得西凉世子燕洵暗中相救，随后她被带进权倾朝野的门阀宇文家。</p>
	    		<img src="img/3.png" alt="">
	    	</div>
	    </div>
```

Q:为什么说是文字环绕效果的衍生呢？
A:上面的margin-left/padding-left如果是0 ，就是文字环绕效果
![image](https://user-images.githubusercontent.com/28972785/28500441-07158c3a-6ffb-11e7-8335-bcf6296fb8ce.png)

* **DOM与显示位置问题**
![image](https://user-images.githubusercontent.com/28972785/28500447-2066206e-6ffb-11e7-8601-d659c20d8bf9.png)

对于这种布局，右侧固定左侧自适应CSS和上面可以一样：

```css
 .tx-img{
        	width:100px;
        	float: right;
        	margin-left: 20px;
        }
        .des{
        	margin-right: 120px;
        }
```
> 存在问题？就是这样DOM树和我们直观看到的不一致，在HTML里面头像图片其实是在前面的，描述是在后面的；但是看上去是描述在前面，头像在后面；

Q:如何做到不改变DOM位置的流体布局呢？
A:我们用正常的视觉看到的DOM写，在描述部分外面加一层DIV

```css
.tx{
        	float: left;
        	margin-left: -100px;
        	width: 100px;
        }
        .full-float{
        	width:100%;
        	float: left;
        }
        .des{
        	margin-right: 120px;
        }
```

```html
<div class="box-con">
	       <div class="full-float">
    	    	<div class="des">
    	    		<p>西魏年间乱世混战，大批平民在战乱中沦为
     奴隶，命如草芥。奴籍少女楚乔（赵丽颖饰）</p>
    	    		<div>
    	    			<img src="img/2.png" alt="">
    	    		</div>
    	    	</div>	
	       </div>
	    	<a href="javaScript;" class="tx">
	    		<img src="img/1.png" alt="">
	    	</a>
	    </div>
```

## 左右两侧全部自适应

之前的布局我们把头像的宽度是定死的，如果头像的宽度变宽，怎会出现这样的情况，我们换一个大一点的头像；

![image](https://user-images.githubusercontent.com/28972785/28500635-30ad4fda-6ffe-11e7-9bd1-a4daac739e2a.png)

Q：如何做到左边头像不是固定，头像宽度变宽，右侧依然不影响
![image](https://user-images.githubusercontent.com/28972785/28500642-56f90238-6ffe-11e7-8fc7-c7889484f5ef.png)

固定套路：

![image](https://user-images.githubusercontent.com/28972785/28500657-9d7b40ea-6ffe-11e7-8f4a-115d1fcc5171.png)

```css
.left{
        	float: left;
        	margin-right: 20px;
        }
        .right{
        	margin-left: 120px;
        }
        .right-cell{
        	display: table-cell;
        	width: 2000px;
        	*display: inline-block; 
        }
```

## float兼容性
